// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCnnXpWvxuBZQ2jds84Ai48pqlcsLu3Y',
    appId: '1:734685165889:web:8ea2ec3c4435a0e89a09c0',
    messagingSenderId: '734685165889',
    projectId: 'essaouira-380b0',
    authDomain: 'essaouira-380b0.firebaseapp.com',
    storageBucket: 'essaouira-380b0.appspot.com',
    measurementId: 'G-H4FD0BWGXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrb-rLqfZObjKNywGHy_zW_jEabRI-mk',
    appId: '1:734685165889:android:559f7c01aff8b2459a09c0',
    messagingSenderId: '734685165889',
    projectId: 'essaouira-380b0',
    storageBucket: 'essaouira-380b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCcIWre-06ZddF0_3IMmh3Ff5A-rGIdg',
    appId: '1:734685165889:ios:a9e0e213225f84e79a09c0',
    messagingSenderId: '734685165889',
    projectId: 'essaouira-380b0',
    storageBucket: 'essaouira-380b0.appspot.com',
    iosClientId: '734685165889-592lj31nvvn8m7sohosiub2ft5da2cnc.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
